name: Báo cáo Bug
description: Báo cáo vấn đề và Bug gặp phải khi sử dụng Slimefun 4
labels:
  - "🐞 Bug"

body:
  - type: markdown
    attributes:
      value: |
        Cảm ơn bạn đã sử dụng hệ thống báo cáo vấn đề Slimefun!

        Trước khi báo cáo, vui lòng xác nhận
        - Bạn đã kiểm tra [phiên bản mới nhất](https://github.com/SlimefunGuguProject/Slimefun4/releases) đã sửa vấn đề bạn gặp phải chưa
        - Bạn đã tìm kiếm các [vấn đề](https://github.com/SlimefunGuguProject/Slimefun4/issues) hiện có để xem có vấn đề tương tự không
        
        Nếu báo cáo của bạn mơ hồ hoặc không tuân theo mẫu, chúng tôi sẽ đóng trực tiếp.

  - type: textarea
    id: issue-description
    attributes:
      label: Mô tả vấn đề
      description: Mô tả chi tiết vấn đề bạn gặp phải
    validations:
      required: true

  - type: dropdown
    id: reproducibility
    attributes:
       label: Tỷ lệ tái hiện vấn đề
       description: Chọn xác suất xảy ra vấn đề
       options:
         - Không thể tái hiện
         - Thỉnh thoảng thấp
         - Thỉnh thoảng cao
         - Luôn xảy ra
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Các bước tái hiện
      description: Mô tả ngắn gọn cách để chúng tôi tái hiện vấn đề này
      placeholder: |
        Mô tả ngắn gọn cách để chúng tôi tái hiện vấn đề này
        Có thể dùng định dạng danh sách 1.  2.  3.  hoặc bất kỳ định dạng phù hợp nào khác
        Nếu vấn đề này khó tái hiện, hãy cố gắng mô tả tình huống khi nó xảy ra
    validations:
      required: true

  - type: dropdown
    id: server-platform-type
    attributes:
      label: Loại server
      description: |
        Chọn server bạn đang sử dụng, ví dụ `Paper`
        Lưu ý: Repo bản Hán hóa không hỗ trợ **hybrid server** (như Arclight, CatServer - loại server hỗ trợ plugin và Mod cùng tồn tại), vui lòng tự giải quyết
      options:
        - Paper
        - Leaves
        - Purpur
        - Airplane
        - Pufferfish
        - Leaf
        - Mirai
        - Server khác (vui lòng nêu rõ trong `Mô tả vấn đề`)
    validations:
      required: true

  - type: dropdown
    id: minecraft-version
    attributes:
      label: Phiên bản Minecraft
      options:
        - 26.2.x
        - 26.1.x
        - 1.21.x
        - 1.20.x
        - 1.19.x
        - 1.18.x
        - 1.17.x
        - 1.16.x
        - 1.15.x
        - 1.14.x
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    validations:
      required: true
    attributes:
      label: Phiên bản Slimefun
      description: |
        **Không được điền "phiên bản mới nhất", nếu không báo cáo của bạn sẽ bị đóng ngay lập tức**
        Vui lòng chụp ảnh hoặc sao chép kết quả sau khi chạy lệnh "/sf versions".
      placeholder: Slimefun 2025.1

  - type: textarea
    id: other-plugin
    attributes:
      label: Danh sách plugin server
      description: Cung cấp danh sách plugin của server, bạn có thể lấy bằng lệnh /plugins.
      placeholder: |
        Plugin: Phiên bản

  - type: textarea
    id: additional
    attributes:
      label: Thông tin bổ sung
      description: Nếu cần thiết, bạn có thể tiếp tục thêm thông tin khác bên dưới
