blank_issues_enabled: true
contact_links:
  - name: Không có tài khoản Github? Không biết dùng Github?
    url: https://docs.qq.com/form/page/DSlFOZmpTQ1JsZ2FD
    about: Nhấp vào đây để điền phản hồi Bug bằng Tencent Docs