name: Phản hồi bản dịch
description: Phản hồi vấn đề bản dịch của Slimefun 4
labels:
- "📜 Translation | Vấn đề bản dịch"

body:
- type: markdown
  attributes:
    value: |
      Cảm ơn bạn đã sử dụng hệ thống phản hồi vấn đề Slimefun!
      
      Trước khi phản hồi, vui lòng xác nhận
      - Bạn đã kiểm tra [phiên bản mới nhất](https://github.com/SlimefunGuguProject/Slimefun4/releases) đã sửa vấn đề bạn gặp phải chưa
      - Bạn đã tìm kiếm các [vấn đề](https://github.com/SlimefunGuguProject/Slimefun4/issues) hiện có để xem có vấn đề tương tự không
      
      Nếu phản hồi của bạn mơ hồ hoặc không tuân theo mẫu, chúng tôi sẽ đóng trực tiếp.

- type: textarea
  id: issue-description
  attributes:
    label: Mô tả vấn đề bản dịch
    description: Mô tả chi tiết vấn đề bạn gặp phải
  validations:
    required: true

- type: textarea
  id: reproduce
  attributes:
    label: Vị trí bản dịch sai/thiếu
    description: Mô tả ngắn gọn vị trí bản dịch sai/thiếu
  validations:
    required: true

- type: textarea
  id: slimefun-version
  validations:
    required: true
  attributes:
    label: Phiên bản Slimefun
    description: |
      **Không được điền "phiên bản mới nhất", nếu không phản hồi của bạn sẽ bị đóng ngay lập tức**
      Vui lòng chụp ảnh hoặc sao chép kết quả sau khi chạy lệnh "/sf versions".
    placeholder: Slimefun 2025.1

- type: textarea
  id: additional
  attributes:
    label: Thông tin bổ sung
    description: Nếu cần thiết, bạn có thể tiếp tục thêm thông tin khác bên dưới
