# This workflow will build a Java project with Gradle

name: Slimefun Dev CI

on:
  workflow_call:
  workflow_dispatch:

env:
  TZ: 'Asia/Shanghai'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x gradlew
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ vars.JAVA_CI_VERSION || 21 }}
          java-package: jdk
          architecture: x64
          cache: gradle
      # - name: Publish snapshots
      #   run: |
      #     echo "::add-mask::$MAVEN_ACCOUNT"
      #     echo "::add-mask::$MAVEN_PASSWORD"
      #     ./gradlew publish -Pversioning.disable --no-daemon
      #   env:
      #     MAVEN_ACCOUNT: '${{ secrets.MAVEN_ACCOUNT }}'
      #     MAVEN_PASSWORD: '${{ secrets.MAVEN_PASSWORD }}'
      - name: Environment Setup
        id: env-setup
        run: |
          SHORT_COMMIT_HASH=$(git rev-parse --short=8 ${{ github.sha }})
          JAR_VERSION="Build-$SHORT_COMMIT_HASH"
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> "$GITHUB_ENV"
          echo "SHORT_COMMIT_HASH=$SHORT_COMMIT_HASH" >> "$GITHUB_OUTPUT"
          echo "JAR_VERSION=$JAR_VERSION" >> "$GITHUB_ENV"
      - name: Build Slimefun
        run: ./gradlew clean build -PprojectVersion="$JAR_VERSION" --no-daemon
      - name: Get build artifact filename
        run: |
          FILENAME=$(find build/libs -maxdepth 1 -type f -name "Slimefun-*.jar" ! -name "*-sources.jar" -printf "%f\n")
          [ -n "$FILENAME" ]
          [ "$(printf "%s\n" "$FILENAME" | wc -l)" -eq 1 ]
          echo "SLIMEFUN_ARTIFACT_NAME=$FILENAME" >> "$GITHUB_ENV"
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.SLIMEFUN_ARTIFACT_NAME }}
          path: build/libs/${{ env.SLIMEFUN_ARTIFACT_NAME }}